### ISSUE TITLE
Реворк работы админа

### ISSUE THREAD

**Issue by vivivixmc** [ZipZipa/support_bot#10]
1. Брать значение кто админ а кто нет из таблы в бд а не из енва. Почему? Потому, что потом когда он будет лежать на серваке что бы выдать кому то надо будет править енв на хосте. 
2. Фича для кнопки admin, не только добавит кнопку но и выдать админа. Пример: какой то админ попросил админа себе выдать. Он пишет /admin и получает свой айдишник. Присылает другому админу, он уже нажимает кнопку админ-добавить админа- вводит айдишник. Далее это значение прописывается в таблу (мб булевый столбец 1-админ 0-не админ, или вообще если он там есть значит по-любому админ) 

P.S. Помозговать может применить 2 роли: модератор(может добавлять кнопки(перспективно удалять)) и админ (может добавлять модеров/админов)

**Comment by ZipZipa** [comment]
3. настройка админского меню
