### ISSUE TITLE
Ограничить длину кнопки

### ISSUE THREAD

**Issue by boriseus** [ZipZipa/support_bot#12]
Необходимо ограничить длину строки на вход для заголовка кнопки.

**Comment by boriseus** [comment]
@ZipZipa @vivivixmc во сколько символов устанавливаем лимит?

Нужен ли лимит для rez_pages?

**Comment by vivivixmc** [comment]
Для лимита рез Пейдж это кол-во символов которое телега может переварить в одном сообщении

**Comment by boriseus** [comment]
Для заголовка лимит 16 символов на строку @vivivixmc

**Comment by boriseus** [comment]
Какова целесообразность разбивать заголовок на 2 строки? Не поедет ли из-за этого верстка меню?

**Comment by vivivixmc** [comment]
> 

Предполагаю, что это просто растянет вертикально кнопки
Типа сейчас так
|кнопка||строка1|
Будет 
|             ||строка 1|
|кнопка||               |
|             ||строка 2|

**Comment by boriseus** [comment]
Инлайн-клавиатура не умеет в два ряда. На текущий момент имеем ограничение в 17 символов на 1 ряд.
