### ISSUE TITLE
[ASAP] Удаление кнопок

### ISSUE THREAD

**Issue by ZipZipa** [ZipZipa/support_bot#22]
Реализовать рекурсивное удаление (с подтверждением) кнопок начиная с текущего уровня вложенности

**Comment by boriseus** [comment]
Как я вижу это визуально:

1. Дорисовываем к "добавить кнопку" в один ряд пункт "удалить кнопку".
2. Когда нажимаем "удалить кнопку" (входим в FSM?) у нас перерисовывается клавиатура текущего уровня, где к каждой кнопке добавляется текст "удалить".
3. При нажатии на кнопку, например "Удалить ЕФС" появляется подтверждение: "Действительно удалить "ЕФС" и все содержащиеся в ней кнопки?" (выводить кнопки внутри?) Да/Нет
4. Само удаление происходит через джойны из таблиц main_pages, rez_pages
5. PROFIT

Как я вижу это программно:
🐒
