### ISSUE TITLE
После отмены создания кнопки не появляется кнопка админа

### ISSUE THREAD

**Issue by boriseus** [ZipZipa/support_bot#47]

**Comment by boriseus** [comment]
Ошибка возникает из-за того, что клавиатуру с вариантами кнопок нам отправляет бот, а не мы вызываем сами из чата. Соответственно id отправителя этого сообщения, который идентифицируется в show_menu будет сам бот. Как временное решение - добавить в .env id бота в качестве админа. Прошу всех ознакомиться. @vivivixmc @ZipZipa

**Comment by vivivixmc** [comment]
> Как временное решение - добавить в .env id бота в качестве админа. Прошу всех ознакомиться. @vivivixmc @ZipZipa 

Я не против, то что сам бот будет админом, думаю он не человек не по плану не пойдёт)
