### ISSUE TITLE
Вычистка в Rez_page

### ISSUE THREAD

**Issue by vivivixmc** [ZipZipa/support_bot#56]
Необходимо вычищать не используемые (Без ссылок на них) строки в таблице rez_page 
Предлагаю след систему
Раз в сутки например в 00:00 будет запускаться скрипт который:
1 собирает пул из main_page по столбцу rez_id и пул в rez_page пул с айдишниками
2 сравнивает их и убирает из второго пула все совпадения с первым
3 запускает запрос в бд delete from Rez_page where оставшиеся значения

@ZipZipa @boriseus что думаете над такой концепцией? 

Так же можно утяжеловесить функцию которая удаляет кнопки

**Comment by boriseus** [comment]
@vivivixmc норм, надо будет настраивать cron на серваке.

**Comment by boriseus** [comment]
@vivivixmc что если вычищать эту таблицу функцией delete_button_children?
