### ISSUE TITLE
При удалении Рекурсия возвращает все кнопки с одинаковым именем

### ISSUE THREAD

**Issue by boriseus** [ZipZipa/support_bot#63]
@vivivixmc пока ошибку удалось локализировать только здесь:
ЕФС->Удалить кнопку->Общая информация

В удаление прилетает кнопка ППРБ->Общая информация

**Comment by vivivixmc** [comment]
Дак кнопки выводит не рекурсия а запрос в бд

**Comment by vivivixmc** [comment]
А блин, понял

**Comment by vivivixmc** [comment]
Проблема не воспроизвелась ![image](https://user-images.githubusercontent.com/25049605/172820680-2b4b5be5-7730-423a-af9c-5a6ea6535797.png)

**Comment by vivivixmc** [comment]
Удалил то что надо ![image](https://user-images.githubusercontent.com/25049605/172820915-8db49dd4-58d9-4768-ae49-2ac8a32bbaf7.png)

**Comment by vivivixmc** [comment]
Проблема в индексах кнопок созданных в ручную, они ведут на 0 уровень, надо пересоздать бд и заполнить ее через конструктор

**Comment by vivivixmc** [comment]
Бага не в ДБ а рекурсии в функции addNode

**Comment by ZipZipa** [comment]
Исправлено, мерж в дев
