### ISSUE TITLE
ValueError: Resulted callback data is too long! Отредачить CBD чтоб убрать проблему 

### ISSUE THREAD

**Issue by vivivixmc** [ZipZipa/support_bot#9]
Что бы не забыть идею
у нас в CBD  летит следующее
"data": "menu:3851107:34534534534534534:0:3851107:3851078"}}
а то есть "???:след ур кнопки:Текст кнопки:last:айди ответа:текущий уровень"
наглядно видим что мы можем сэкономить размер путем убирания дубля, :**след ур кнопки**: и :**айди ответа**:
"data": "menu:**3851107**:34534534534534534:0:**3851107**:3851078"}}

далее мы можем не передавать сам текст кнопки, а давать на него "_id" вместо :**34534534534534534**: мы можем взять **76**
![Screenshot 2022-05-30 at 00 17 42](https://user-images.githubusercontent.com/25049605/170887809-7e5f78a2-9dec-477f-9c95-fa7e798b7c23.png)

тем более он прилетает нам из cur.fetchall()

**Comment by vivivixmc** [comment]
+ добавить лимит на текст в кнопке, всеравно не видно

тк мы можем впихнуть все что угодно в в название кнопки по длине мы не ограничены, проблема в отображении

**Comment by ZipZipa** [comment]
убран параметр rez_id из cb
